modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Floating-Rails/issues"

[[mods]]
modId="floatingrails"
version="${file.jarVersion}"
displayName="Floating Rails"
displayURL="https://www.curseforge.com/minecraft/mc-mods/floating-rails"
credits=""
authors="Ewy"
description=""

[[dependencies.floatingrails]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.floatingrails]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3, 1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.floatingrails]]
modId="bibliotheca"
mandatory=true
versionRange="[1.6.2,)"
ordering="NONE"
side="BOTH"