package com.ewyboy.floatingrails.Crafting;

import com.ewyboy.floatingrails.Content.Technical.BlocksAndItems;
import com.ewyboy.floatingrails.Rails.Technical.Rails;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;

public class CraftingRecipes {

    public static void Init() {
        registerCrafting();
    }

    public static void registerCrafting() {

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,1), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,2), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,3), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,4), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,5), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,6), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,7), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawner,8), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,1), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,2), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,3), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,4), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,5), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,6), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,7), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerPowered,8), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,1), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,2), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,3), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,4), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,5), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,6), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,7), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerDetection,8), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,1), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,2), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,3), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,4), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,5), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,6), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,7), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerActivation,8), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,1), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,2), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,3), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,4), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,5), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,6), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,7), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailLavaSpawner,8), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail), new ItemStack(Blocks.rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,1), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,2), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,3), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail ));
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,4), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail ), new ItemStack(Blocks.golden_rail));
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,5), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail ), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail));
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,6), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail ), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail));
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,7), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail ), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail));
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaPowered,8), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail ), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail), new ItemStack(Blocks.golden_rail));

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,1), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,2), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,3), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,4), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,5), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,6), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,7), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaDetection,8), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail), new ItemStack(Blocks.detector_rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,1), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,2), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,3), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,4), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,5), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,6), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,7), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );
        GameRegistry.addShapelessRecipe(new ItemStack(Rails.FloatingRailSpawnerLavaActivation,8), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail), new ItemStack(Blocks.activator_rail) );

        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,1), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,2), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,3), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,4), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,5), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,6), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,7), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingTorchSpawner,8), new ItemStack(Blocks.waterlily), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );

        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,1), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,2), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,3), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,4), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,5), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,6), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,7), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );
        GameRegistry.addShapelessRecipe(new ItemStack(BlocksAndItems.FloatingLavaTorchSpawner,8), new ItemStack(BlocksAndItems.LavaLilySpawner), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch), new ItemStack(Blocks.redstone_torch) );

    }
}
